SHOW SCHEMAS;
SHOW DATABASES;
USE sys;
SELECT * FROM mysql.db;
SELECT * FROM mysql.USER;
SELECT USER();
USE mysql;
SHOW COLUMNS FROM mysql.db; -- addressaddressaddress
SHOW TABLES;
USE db_autogenerated; -- error de que no esta
DESCRIBE mysql.db;
SHOW COLUMNS FROM mysql.db;