-- MySQL Script generated by MySQL Workbench
-- Wed Aug 17 23:46:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genre` (
  `idGenre` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Genre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idGenre`, `Genre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Artist` (
  `idArtist` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `artistName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idArtist`, `artistName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Album` (
  `idAlbum` INT UNSIGNED NOT NULL,
  `albumName` VARCHAR(255) NOT NULL,
  `datereleased` DATETIME NOT NULL,
  `Artist_idArtist` INT UNSIGNED NOT NULL,
  `Artist_artistName` VARCHAR(255) NOT NULL,
  `Genre_idGenre` INT UNSIGNED NOT NULL,
  `Genre_Genre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idAlbum`, `albumName`, `datereleased`, `Genre_idGenre`, `Genre_Genre`),
  INDEX `fk_Album_Artist_idx` (`Artist_idArtist` ASC, `Artist_artistName` ASC) VISIBLE,
  INDEX `fk_Album_Genre1_idx` (`Genre_idGenre` ASC, `Genre_Genre` ASC) VISIBLE,
  CONSTRAINT `fk_Album_Artist`
    FOREIGN KEY (`Artist_idArtist` , `Artist_artistName`)
    REFERENCES `mydb`.`Artist` (`idArtist` , `artistName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Album_Genre1`
    FOREIGN KEY (`Genre_idGenre` , `Genre_Genre`)
    REFERENCES `mydb`.`Genre` (`idGenre` , `Genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ejercicio66`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ejercicio66` (
  `idejercicio66` INT NOT NULL,
  `textomugrande` VARCHAR(45) NULL,
  `entero` INT NULL,
  `ejercicio66col` VARCHAR(45) NULL,
  `decimal` DOUBLE NULL,
  `ejercicio66col1` VARCHAR(45) NULL,
  PRIMARY KEY (`idejercicio66`))
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
